# Generated by Django 4.2.3 on 2023-08-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_latitiude_statecommittee_latitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="needs",
            name="state_committee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.statecommittee",
            ),
        ),
    ]
