# Generated by Django 4.2.3 on 2023-08-01 13:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_needs_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alert",
            name="is_verified_by_admin",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alert",
            name="rejected_by",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="state_committee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.statecommittee",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
