# Generated by Django 4.2.3 on 2023-08-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alert_created_alert_is_verified_by_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="remark",
        ),
        migrations.AddField(
            model_name="alert",
            name="content",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
