# Generated by Django 4.2.3 on 2023-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_alert_remark_alert_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={"ordering": ["-created", "-updated"]},
        ),
        migrations.AddField(
            model_name="alert",
            name="is_verified_by_state",
            field=models.IntegerField(default=0),
        ),
    ]
