# Generated by Django 4.2.3 on 2023-08-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_alert_options_alert_is_verified_by_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("amount", models.BigIntegerField(null=True)),
                ("status", models.IntegerField(default=0)),
                (
                    "volunteer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.volunteer",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated", "-created"],
            },
        ),
    ]
