# Generated by Django 4.2.3 on 2023-08-09 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="alert",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.needs"
            ),
        ),
    ]
