# Generated by Django 4.2.3 on 2023-08-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_certificate_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="needs",
            name="cr_status",
            field=models.IntegerField(default=0),
        ),
    ]
