# Generated by Django 4.2.3 on 2023-08-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_needs_cr_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="alert",
            new_name="need",
        ),
    ]
