# Generated by Django 4.2.3 on 2023-08-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_rename_alert_certificate_need"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="estimate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates"),
        ),
    ]
