# Generated by Django 4.2.3 on 2023-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_certificate_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="estimate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates"),
        ),
    ]
