# Generated by Django 5.0.3 on 2024-03-21 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_estimatecost"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimname", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("claimtype", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="certificates"),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "userid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
