# Generated by Django 5.0.3 on 2024-03-22 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_userclaim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task_voluenteers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskdescriprion", models.CharField(max_length=255, null=True)),
                (
                    "alertid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.alert",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.statecommittee",
                    ),
                ),
                (
                    "volunteerid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.volunteer",
                    ),
                ),
            ],
        ),
    ]
