# Generated by Django 5.0.3 on 2024-03-22 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_rename_task_voluenteers_task_voluenteer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="userid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
